[package]
name = "mush"
version = "0.1.0"
description = "Mush, a build system for shell."
license = "MIT"
edition = "2022"

[dependencies]
console = "mush javanile/mush/console"
getoptions = "mush javanile/mush/getoptions"

[dev-dependencies]
shellcheck = "apt shellcheck"
