title: "Mush"
remote_theme: "just-the-docs/just-the-docs@main"
url: "https://mush.javanile.org"

plugins:
  - jekyll-sitemap

aux_links:
  "<img src='/assets/img/github.svg'/>":
    - "https://github.com/javanile/mush"
  "<img src='/assets/img/discord.svg'/>":
    - "https://discord.gg/SVx7JHjAcY"
  "<img src='/assets/img/whatsapp.svg'/>":
    - "https://chat.whatsapp.com/Lt7wfx0wU8yKb8d9SFINUE"

footer_content: >
  Â© 2024 Francesco Bianco. All rights reserved.
  <script>document.querySelector('div.site-header a').innerHTML = 'ğŸ„ Mush<sup>BETA</sup>';</script>  
  <script async src="https://scripts.simpleanalyticscdn.com/latest.js"></script>

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
