title: "ğŸ„ Mush"
remote_theme: just-the-docs/just-the-docs@main

aux_links:
  "<img src='/assets/img/github.svg'/>":
    - "https://github.com/javanile/mush"
  #"<img src='/assets/img/twitter.svg'/>":
  #  - "https://twitter.com/hashtag/MushDev"
  "<img src='/assets/img/discord.svg'/>":
    - "https://discord.gg/SVx7JHjAcY"
